export interface Product {
  id: number;
  name: string;
  price: number;
  mrp: number;
  rating: number;
  reviews: number;
  image: string;
  images?: string[];
  badge?: string;
  isBestSeller?: boolean;
  emiText?: string;
  discount: number;
  category?: string;
  description?: string;
  stock?: number;
}

export const products: Product[] = [
  // Sofas
  {
    id: 1,
    name: 'Solid Wood Sofa Set',
    price: 24999,
    mrp: 49999,
    rating: 4.5,
    reviews: 234,
    image: '/sofa.png',
    images: ['/sofa.png', '/sofa.png', '/sofa.png', '/sofa.png'],
    badge: 'Sale',
    isBestSeller: true,
    emiText: 'From ₹1,042/month',
    discount: 50,
    category: 'sofas',
    description: 'Premium solid wood sofa set crafted from high-quality sheesham wood. Features comfortable seating for 3 people with durable fabric upholstery. Perfect for modern living rooms with elegant design and superior comfort.',
    stock: 15,
  },
  {
    id: 9,
    name: 'Sectional L-Shaped Sofa',
    price: 34999,
    mrp: 69999,
    rating: 4.8,
    reviews: 312,
    image: '/sofa.png',
    badge: 'Sale',
    isBestSeller: true,
    emiText: 'From ₹1,458/month',
    discount: 50,
    category: 'sofas',
  },
  {
    id: 10,
    name: 'Modern Fabric Sofa',
    price: 19999,
    mrp: 39999,
    rating: 4.6,
    reviews: 178,
    image: '/sofa.png',
    badge: 'Sale',
    emiText: 'From ₹833/month',
    discount: 50,
    category: 'sofas',
  },
  {
    id: 11,
    name: 'Premium Reclining Sofa',
    price: 44999,
    mrp: 89999,
    rating: 4.7,
    reviews: 256,
    image: '/sofa.png',
    badge: 'Sale',
    isBestSeller: true,
    emiText: 'From ₹1,875/month',
    discount: 50,
    category: 'sofas',
  },

  // Beds
  {
    id: 2,
    name: 'Sheesham Wood Bed',
    price: 18999,
    mrp: 35999,
    rating: 4.7,
    reviews: 189,
    image: '/bed.png',
    badge: 'Sale',
    emiText: 'From ₹791/month',
    discount: 47,
    category: 'beds',
  },
  {
    id: 12,
    name: 'King Size Wooden Bed',
    price: 26999,
    mrp: 53999,
    rating: 4.6,
    reviews: 203,
    image: '/bed.png',
    badge: 'Sale',
    isBestSeller: true,
    emiText: 'From ₹1,125/month',
    discount: 50,
    category: 'beds',
  },
  {
    id: 13,
    name: 'Classic Double Bed',
    price: 15999,
    mrp: 31999,
    rating: 4.5,
    reviews: 142,
    image: '/bed.png',
    badge: 'Sale',
    emiText: 'From ₹666/month',
    discount: 50,
    category: 'beds',
  },
  {
    id: 14,
    name: 'Platform Bed Frame',
    price: 12999,
    mrp: 25999,
    rating: 4.4,
    reviews: 98,
    image: '/bed.png',
    emiText: 'From ₹541/month',
    discount: 50,
    category: 'beds',
  },

  // Dining Sets
  {
    id: 3,
    name: 'Dining Table & 6 Chairs',
    price: 28999,
    mrp: 59999,
    rating: 4.6,
    reviews: 156,
    image: '/dinning.png',
    badge: 'Sale',
    isBestSeller: true,
    emiText: 'From ₹1,208/month',
    discount: 52,
    category: 'dining-sets',
  },
  {
    id: 15,
    name: 'Modern Dining Table Set',
    price: 19999,
    mrp: 39999,
    rating: 4.5,
    reviews: 134,
    image: '/dinning.png',
    badge: 'Sale',
    emiText: 'From ₹833/month',
    discount: 50,
    category: 'dining-sets',
  },
  {
    id: 16,
    name: 'Glass Top Dining Table',
    price: 24999,
    mrp: 49999,
    rating: 4.4,
    reviews: 112,
    image: '/dinning.png',
    emiText: 'From ₹1,042/month',
    discount: 50,
    category: 'dining-sets',
  },
  {
    id: 17,
    name: 'Compact 4 Seater Dining Set',
    price: 14999,
    mrp: 29999,
    rating: 4.6,
    reviews: 167,
    image: '/dinning.png',
    badge: 'Sale',
    emiText: 'From ₹625/month',
    discount: 50,
    category: 'dining-sets',
  },

  // Storage
  {
    id: 4,
    name: 'Storage Cabinet',
    price: 12999,
    mrp: 25999,
    rating: 4.4,
    reviews: 87,
    image: '/storage.jpg',
    badge: 'Sale',
    emiText: 'From ₹541/month',
    discount: 50,
    category: 'storage',
  },
  {
    id: 6,
    name: 'Wall Mounted Shelf',
    price: 4999,
    mrp: 9999,
    rating: 4.2,
    reviews: 102,
    image: '/storage.jpg',
    emiText: 'From ₹208/month',
    discount: 50,
    category: 'storage',
  },
  {
    id: 7,
    name: 'Wooden Bookshelf',
    price: 14999,
    mrp: 29999,
    rating: 4.5,
    reviews: 145,
    image: '/storage.jpg',
    badge: 'Sale',
    emiText: 'From ₹625/month',
    discount: 50,
    category: 'storage',
  },
  {
    id: 18,
    name: 'Multi-Drawer Storage Unit',
    price: 9999,
    mrp: 19999,
    rating: 4.3,
    reviews: 76,
    image: '/storage.jpg',
    emiText: 'From ₹416/month',
    discount: 50,
    category: 'storage',
  },

  // Other products
  {
    id: 5,
    name: 'Office Desk with Drawer',
    price: 9999,
    mrp: 19999,
    rating: 4.3,
    reviews: 64,
    image: '/office.webp',
    emiText: 'From ₹416/month',
    discount: 50,
  },
  {
    id: 8,
    name: 'Coffee Table',
    price: 7999,
    mrp: 15999,
    rating: 4.4,
    reviews: 98,
    image: '/sofa.png',
    emiText: 'From ₹333/month',
    discount: 50,
  },
];
